Vagrant.configure(2) do |config|
  config.vm.box = "CentOS66_x64"
  
  # 環境に合わせてネットワーク周りの設定。
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network",ip: "192.168.11.129"
  
  # 共有フォルダ
  # config.vm.synced_folder "../data", "/vagrant_data"

  # 共有フォルダ /vagrant は変更しない
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777,fmode=777"]
  
  # ECCUBE2系環境セットアップ
  config.vm.provision :shell, :path => "install_eccube2_enviroment.sh"
  # ECCUBE2本体インストール（本体が不要な場合はコメントアウト）
  config.vm.provision :shell, :path => "install_eccube2_13_5.sh"

  # synced_folderをドキュメントルートにするので、毎回httpd起動コマンド叩く
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    sudo service httpd start
  SHELL
end
